-- AlterEnum: add MONTHLY_CLAIM_SETTLEMENT to WorkEventType
ALTER TABLE `WorkEvent` MODIFY `eventType` ENUM(
  'HOLIDAY_WORK_RECORDED',
  'CR_CREDIT_ISSUED',
  'CR_CONSUMED',
  'CR_EXPIRED',
  'LEAVE_RECORDED',
  'LEAVE_LEDGER_ADJUSTMENT',
  'LEAVE_CONVERSION',
  'NIGHT_DUTY_RECORDED',
  'TRAVEL_RECORDED',
  'MONTHLY_CLAIM_SETTLEMENT',
  'BILL_SUBMITTED',
  'CLAIM_PASSED',
  'PAYMENT_RECEIVED',
  'STATUS_CHANGED',
  'ATTACHMENT_LINKED',
  'NOTE_AMENDED',
  'EVENT_VOIDED'
) NOT NULL;
